# Package Overview
package_name: classification_model

# Data Files
training_data_file: train.csv
test_data_file: test.csv
sample_train_data_file: sample_train_data.csv
csv_format: csv

# Set train/test split
test_size: 0.1

# Set the random seed
random_state: 123

# Threshold for NaN
na_thresh: 0

# Variables
pipeline_name: classification_model
pipeline_save_file: classification_model_output_v

target: loan_status

features:
  - acc_now_delinq
  - addr_state
  - all_util
  - annual_inc
  - application_type
  - collections_12_mths_ex_med
  - delinq_2yrs
  - dti
  - emp_length
  - grade
  - home_ownership
  - il_util
  - initial_list_status
  - inq_fi
  - inq_last_12m
  - inq_last_6mths
  - int_rate
  - last_pymnt_amnt
  - loan_amnt
  - max_bal_bc
  - mths_since_last_delinq
  - mths_since_last_major_derog
  - mths_since_rcnt_il
  - open_acc
  - open_acc_6m
  - open_il_12m
  - open_il_24m
  - open_rv_12m
  - out_prncp
  - pub_rec
  - purpose
  - recoveries
  - revol_bal
  - revol_util
  - term
  - tot_coll_amt
  - tot_cur_bal
  - total_acc
  - total_bal_il
  - total_cu_tl
  - total_pymnt
  - total_rec_int
  - total_rec_late_fee
  - total_rev_hi_lim
  - verification_status
  # - zip_code

num_vars_to_drop:
  - annual_inc_joint
  - collection_recovery_fee
  - dti_joint
  - funded_amnt
  - funded_amnt_inv
  - id
  - installment
  - member_id
  - mths_since_last_record
  - open_rv_24m
  - out_prncp_inv
  - total_pymnt_inv
  - total_rec_prncp

cat_vars_to_drop:
  - desc
  - earliest_cr_line
  - emp_title
  - issue_d
  - last_credit_pull_d
  - last_pymnt_d
  - next_pymnt_d
  - policy_code
  - pymnt_plan
  - sub_grade
  - title
  - verification_status_joint
  - zip_code

# Numerical variables with NA in train set
numerical_vars_with_na:
  - all_util
  - dti
  - il_util
  - inq_fi
  - inq_last_12m
  - inq_last_6mths
  - max_bal_bc
  - mths_since_last_delinq
  - mths_since_last_major_derog
  - mths_since_rcnt_il
  - open_acc_6m
  - open_il_12m
  - open_il_24m
  - open_rv_12m
  - revol_util
  - total_bal_il
  - total_cu_tl

categorical_vars_with_na_frequent:
  - emp_length
  # - zip_code

repl_vars_with_median:
  - all_util
  - dti
  - inq_last_6mths
  - mths_since_last_delinq
  - mths_since_last_major_derog

repl_vars_with_mean:
  - il_util
  - inq_fi
  - inq_last_12m
  - max_bal_bc
  - mths_since_rcnt_il
  - open_acc_6m
  - open_il_12m
  - open_il_24m
  - open_rv_12m
  - revol_util
  - total_bal_il
  - total_cu_tl

log_transformed_vars:
  - int_rate
  - total_acc

yeo_johnson_transformed_vars:
  - il_util
  - last_pymnt_amnt
  - max_bal_bc
  - mths_since_last_delinq
  - mths_since_last_major_derog
  - mths_since_rcnt_il
  - open_acc
  - revol_bal
  - tot_cur_bal
  - total_bal_il
  - total_pymnt
  - total_rec_int
  - total_rev_hi_lim

numerical_vars_to_bin:
  - annual_inc
  - delinq_2yrs
  - dti
  - inq_fi
  - inq_last_12m
  - open_il_24m
  - open_rv_12m
  - out_prncp
  - pub_rec
  - recoveries
  - tot_coll_amt
  - total_cu_tl
  - total_rec_late_fee

mapping_vars:
  - emp_length

emp_length_mappings:
  10+ years: 10
  2 years: 2
  < 1 year: 0
  3 years: 3
  1 year: 1
  5 years: 5
  4 years: 4
  6 years: 6
  8 years: 8
  9 years: 9
  7 years: 7

numerical_vars:
  - acc_now_delinq
  - all_util
  - annual_inc
  - collections_12_mths_ex_med
  - delinq_2yrs
  - dti
  - il_util
  - inq_fi
  - inq_last_12m
  - inq_last_6mths
  - int_rate
  - last_pymnt_amnt
  - loan_amnt
  - max_bal_bc
  - mths_since_last_delinq
  - mths_since_last_major_derog
  - mths_since_rcnt_il
  - open_acc
  - open_acc_6m
  - open_il_12m
  - open_il_24m
  - open_rv_12m
  - out_prncp
  - pub_rec
  - recoveries
  - revol_bal
  - revol_util
  - tot_coll_amt
  - tot_cur_bal
  - total_acc
  - total_bal_il
  - total_cu_tl
  - total_pymnt
  - total_rec_int
  - total_rec_late_fee
  - total_rev_hi_lim

continuous_vars:
  - all_util
  - annual_inc
  - delinq_2yrs
  - dti
  - il_util
  - inq_fi
  - inq_last_12m
  - int_rate
  - last_pymnt_amnt
  - loan_amnt
  - max_bal_bc
  - mths_since_last_delinq
  - mths_since_last_major_derog
  - mths_since_rcnt_il
  - open_acc
  - open_il_24m
  - open_rv_12m
  - out_prncp
  - pub_rec
  - recoveries
  - revol_bal
  - revol_util
  - tot_coll_amt
  - tot_cur_bal
  - total_acc
  - total_bal_il
  - total_cu_tl
  - total_pymnt
  - total_rec_int
  - total_rec_late_fee
  - total_rev_hi_lim

discrete_vars:
  - acc_now_delinq
  - collections_12_mths_ex_med
  - inq_last_6mths
  - open_acc_6m
  - open_il_12m

var_with_rare_labels:
  - addr_state
  - collections_12_mths_ex_med
  - emp_length
  - open_acc_6m
  - open_il_12m
  - purpose
  # - zip_code

categorical_vars:
  - addr_state
  - application_type
  - emp_length
  - grade
  - home_ownership
  - initial_list_status
  - purpose
  - term
  - verification_status
  # - zip_code
